name: Re-train ML model

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/retrain.yml'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: spam_env
        environment-file: MLProject/conda.yaml
        auto-activate-base: false

    - name: Run MLflow Project
      run: |
        cd MLProject
        conda run -n spam_env mlflow run .
